name       : perl-test-pod
version    : '1.52'
release    : 8
source     :
    - https://github.com/perl-pod/test-pod/archive/v1.52.tar.gz : 1eeecafeaf9762266f676f2114e1ad06a591ee3507a981325ce0f310219de608
license    : Artistic-1.0-Perl
component  : programming.perl
homepage   : https://github.com/perl-pod/test-pod
summary    : Test::Pod - check for POD errors in files
description: |
    Test::Pod lets you check the validity of a POD file, and report its results in standard Test::Simple fashion.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
