name       : perl-test-pod
version    : 1.51
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/Test-Pod-1.51.tar.gz : c1a1d3cedf4a579e3aad89c36f9878a8542b6656dbe71f1581420f49582d7efb
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Pod - check for POD errors in files
description: |
    Test::Pod lets you check the validity of a POD file, and report its results in standard Test::Simple fashion.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
